// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5EpPtBJzwREEprat-KzAVHpNozYYwFU',
    appId: '1:890509016425:web:3aa67c514d69af133851f8',
    messagingSenderId: '890509016425',
    projectId: 'fluttertp6-fa365',
    authDomain: 'fluttertp6-fa365.firebaseapp.com',
    storageBucket: 'fluttertp6-fa365.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTcO7zYvJj497L6Hs5RqktZ8ipIAZvuE',
    appId: '1:890509016425:android:6778d17ffabdd3433851f8',
    messagingSenderId: '890509016425',
    projectId: 'fluttertp6-fa365',
    storageBucket: 'fluttertp6-fa365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpY0UeHxs_2fS2INx2clADviN1VgvBAc',
    appId: '1:890509016425:ios:0e367da6886028b03851f8',
    messagingSenderId: '890509016425',
    projectId: 'fluttertp6-fa365',
    storageBucket: 'fluttertp6-fa365.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpY0UeHxs_2fS2INx2clADviN1VgvBAc',
    appId: '1:890509016425:ios:0e367da6886028b03851f8',
    messagingSenderId: '890509016425',
    projectId: 'fluttertp6-fa365',
    storageBucket: 'fluttertp6-fa365.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh5EpPtBJzwREEprat-KzAVHpNozYYwFU',
    appId: '1:890509016425:web:fba97152bb8062813851f8',
    messagingSenderId: '890509016425',
    projectId: 'fluttertp6-fa365',
    authDomain: 'fluttertp6-fa365.firebaseapp.com',
    storageBucket: 'fluttertp6-fa365.firebasestorage.app',
  );
}
